/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

#define HSEM_ID_0	0

int main(void)
{
	__BSP_RCC_HSEM_CLK_ENABLE();

	/* Activate HSEM notification for Cortex-M4*/
	BSP_STM32_HSEM_ActivateNotification(HSEM_ID_0);
	/*
	Domain D2 goes to STOP mode (Cortex-M4 in deep-sleep) waiting for Cortex-M7 to
	perform system initialization (system clock config, external memory configuration.. )
	*/
	BSP_STM32_PWR_ClearPendingEvent();
	BSP_STM32_PWR_EnterSTOPMode(PWR_MAINREGULATOR_ON, PWR_STOPENTRY_WFE, PWR_D2_DOMAIN);

	/* Clear HSEM flag */
	BSP_STM32_HSEM_ClearFlag(HSEM_ID_0);

	/* USER CODE END Boot_Mode_Sequence_1 */
	/* MCU Configuration--------------------------------------------------------*/

	/* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	__BSP_RCC_ART_CLK_ENABLE();                   // Enable the Cortex-M4 ART Clock
	__BSP_ART_CONFIG_BASE_ADDRESS(0x08100000UL);  // Configure the Cortex-M4 ART Base address to the Flash Bank 2
	__BSP_ART_ENABLE();                           // Enable the Cortex-M4 ART

	// Set Interrupt Group Priority
	BSP_STM32_NVIC_SetPriorityGrouping(NVIC_PRIORITYGROUP_4);

	uint32_t common_system_clock = BSP_STM32_RCC_GetSysClockFreq() >> ((D1CorePrescTable[(RCC->D1CFGR & RCC_D1CFGR_D1CPRE)>> RCC_D1CFGR_D1CPRE_Pos]) & 0x1FU);
	SystemD2Clock = (common_system_clock >> ((D1CorePrescTable[(RCC->D1CFGR & RCC_D1CFGR_HPRE)>> RCC_D1CFGR_HPRE_Pos]) & 0x1FU));
	SystemCoreClock = SystemD2Clock;

	BSP_TickInit(SystemCoreClock, 1, TICK_INT_PRIORITY);

	__BSP_RCC_SYSCFG_CLK_ENABLE();

	BSP_BOARD_Init_CM4();

	BSP_Delay(6000);


    /* Loop forever */
	for(;;);
}
