/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

int main(void)
{

	if (BSP_BOARD_Init_CM7()) BSP_Error_Handler();

	BSP_LCD_Init(&BSP_hlcd, LCD_COLOR_MODE_ARGB8888, LCD_BUFFER_MODE_DOUBLE, LCD_LAYER_NO_ONE, C_RED, NULL);

	// Initialize Backlight
	BSP_LCD_InitBackLight(&BSP_hlcd, 10);
	BSP_LCD_SetBackLight(&BSP_hlcd, 80, 25);

    /* Loop forever */
	for(;;);
}
